version: '3'
services: 
    client:
        build: 
            context: ./client
        ports: 
            - '3000:3000'
        environment: 
            - REACT_APP_API_URL=http://localhost:5000
        volumes: 
            - ./client:/app
        depends_on: 
            - server
    server:
      build: 
        context: ./server
      ports: 
        - '5000:5000'
      environment: 
        env_file: .env
      volumes: 
        - ./server:/app
      depends_on:
        - db
    db:
      build: 
        context: ./db
      ports: 
        - '5433:5432'
      volumes: 
        - mark-compose-db-vol:/var/lib/postgresql/data
volumes: 
     mark-compose-db-vol: